### PR TITLE
Postprocess navmeshes to work around engine nav mesh baking bugs

### PR DESCRIPTION
**Pull request by tcoxon**
Stop-gap fix for #264 until the underlying engine issues are fixed.

### CODE REVIEW

**Comment by TokisanGames** [comment]
Thank you. I'll merge it in. Functionally this is better and addresses the broken nav mesh generation and the errors. However cosmetically, this creates holes in the nav mesh that aren't there without this post processing. They're all over the place. 

image

They are cosmetic only, as the enemy will happily traverse them.

https://github.com/TokisanGames/Terrain3D/assets/632766/da927b65-7143-40e4-a72d-9ace61eeb467

Do you want to close #264, or mark it as waiting for godot?

**Comment by tcoxon** [comment]
Those holes are just where the navmesh debug polygons drop below the surface of the terrain. If it appears to be new, it's probably just because vertices have moved by up to 0.25 units.

> Do you want to close #264, or mark it as waiting for godot?

Whatever you prefer! We could close it. I'm subscribed to the Godot issue, so when there's a fix I'll get a notification and we can reopen #264 or create a new issue.

**Comment by TokisanGames** [comment]
I tested with and without, and the visual holes are definitely there only after post processing. They make it difficult to determine where the nav mesh is not generated due to slope. `¯\_ (ツ)_/¯`

image

> vertices have moved by up to 0.25 units

Where does this happen?

**Comment by tcoxon** [comment]
> Where does this happen?

`_postprocess_nav_mesh_round_vertices` rounds vertex coordinates to the nearest cell_size/cell_height. The default value for cell_size & cell_height is 0.25.

They're not really holes, they're just the terrain poking through the nav mesh.

**Pull request merged**
